import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import HomePage from '../screens/Home';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomePage></HomePage>
      </main>

      <footer className={styles.footer}>
        Created by Rohit Kumar Das with NextJs
      </footer>
    </div>
  )
}
